




DELETE FROM CCS_SETUP_LOCAL_RANGE WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_STORAGE_RANGE WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_LOCAL_TRANSPORT WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_STORAGE_TEMP WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_OPE_MANAGE WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_OPE_CONSOLIDATION WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_MACRO_VARS WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_EXCHANGES WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_CUSTUM_DUTIES_DETAIL WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_CUSTUM_DUTIES_HEAD WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_STAGE_FREIGHT_OTHER WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_STAGE_FREIGHT_AIR_RANGE WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_STAGE_FREIGHT_AIR WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SITE_SOURCE_TRANSPORT WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_LOCAL_ITEM_MASTER WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_CUSTODY_SERVICE WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_SETUP_LOCAL_ROUTE WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_UNITS_COST WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);
     
DELETE FROM CCS_IMPORT_UNITS WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);

DELETE FROM CCS_STAGE WHERE STG_ID IN (select STG_ID FROM CCS_STAGE WHERE STS_ID = 1);







