

--Consideraciones:
--Se debe cargar las tablas CCS_STAGE_FREIGHT_AIR y CCS_STAGE_FREIGHT_AIR_RANGE inicialmente



DELETE FROM CCS_SITE_SOURCE_TRANSPORT WHERE STG_ID <> 233;

DELETE FROM CCS_LOCAL_ITEM_MASTER WHERE STG_ID <> 233;

DELETE FROM CCS_IMPORT_UNITS WHERE STG_ID <> 233;


DELETE FROM CCS_STAGE_FREIGHT_AIR_RANGE WHERE STG_ID <> 233;

DELETE FROM CCS_STAGE_FREIGHT_AIR WHERE STG_ID <> 233;

DELETE FROM CCS_STAGE WHERE STG_ID <> 233;

commit;





INSERT INTO "MSD_CCS_DB"."CCS_STAGE_FREIGHT_AIR_RANGE" (FRR_ID, FRR_FROM, FRR_TO, FRR_RATE, STG_ID, SIS_ID, FRM_ID) VALUES ('4', '0', '799', '3,2', '233', '2', '1');
INSERT INTO "MSD_CCS_DB"."CCS_STAGE_FREIGHT_AIR_RANGE" (FRR_ID, FRR_FROM, FRR_TO, FRR_RATE, STG_ID, SIS_ID, FRM_ID) VALUES ('5', '800', '1499', '3,2', '233', '2', '1');
INSERT INTO "MSD_CCS_DB"."CCS_STAGE_FREIGHT_AIR_RANGE" (FRR_ID, FRR_FROM, FRR_TO, FRR_RATE, STG_ID, SIS_ID, FRM_ID) VALUES ('6', '1500', '2999', '3,2', '233', '2', '1');


INSERT INTO "MSD_CCS_DB"."CCS_STAGE_FREIGHT_AIR_RANGE" (FRR_ID, FRR_FROM, FRR_TO, FRR_RATE, STG_ID, SIS_ID, FRM_ID) VALUES ('7', '0', '799', '3,2', '233', '2', '2');
INSERT INTO "MSD_CCS_DB"."CCS_STAGE_FREIGHT_AIR_RANGE" (FRR_ID, FRR_FROM, FRR_TO, FRR_RATE, STG_ID, SIS_ID, FRM_ID) VALUES ('8', '800', '1499', '3,2', '233', '2', '2');
INSERT INTO "MSD_CCS_DB"."CCS_STAGE_FREIGHT_AIR_RANGE" (FRR_ID, FRR_FROM, FRR_TO, FRR_RATE, STG_ID, SIS_ID, FRM_ID) VALUES ('9', '1500', '2999', '3,2', '233', '2', '2');



INSERT INTO "MSD_CCS_DB"."CCS_STAGE_FREIGHT_AIR_RANGE" (FRR_ID, FRR_FROM, FRR_TO, FRR_RATE, STG_ID, SIS_ID, FRM_ID) VALUES ('10', '0', '799', '3,2', '233', '1', '2');
INSERT INTO "MSD_CCS_DB"."CCS_STAGE_FREIGHT_AIR_RANGE" (FRR_ID, FRR_FROM, FRR_TO, FRR_RATE, STG_ID, SIS_ID, FRM_ID) VALUES ('11', '800', '1499', '3,2', '233', '1', '2');
INSERT INTO "MSD_CCS_DB"."CCS_STAGE_FREIGHT_AIR_RANGE" (FRR_ID, FRR_FROM, FRR_TO, FRR_RATE, STG_ID, SIS_ID, FRM_ID) VALUES ('12', '1500', '2999', '3,2', '233', '1', '2');


--INSERT CCS_SETUP_CUSTUM_DUTIES_HEAD
--INSERT CCS_SETUP_CUSTUM_DUTIES_DETAIL
--INSERT CCS_SETUP_EXCHANGES
--INSERT CCS_SETUP_MACRO_VARS
--INSERT CCS_SETUP_OPE_CONSOLIDATION


commit;



SELECT UNI.STG_ID, UNI.IMU_COD_PRODUCT, STR.SIS_ID, MAS.LIM_FOB_COST, UNI.IMU_AJUSTED, SMV.SMV_AMOUNT, 8743 as "total freight", SDD.SDD_DUTY_TARIFF, SDD.SDD_OTHER_TAXES, SDH.SDH_OTHER_TAXES_FODINFA, SDH.SDH_VAT_IMPORTS, 
       SDH.SDH_OTHER_TAXES_IMP_CAP, MAS.LIM_UNIT_BY_PALETTE, MAS.LIM_WEIGTH_PALETTE, MAS.LIM_HIGH_PALETTE, MAS.LIM_LARGE_PALETTE, MAS.LIM_WIDE_PALETTE, FAR.FAR_AWB_KG_RATES, STR.SIS_ID, FAR.FAR_FUEL_SURCHARGE, FAR.FAR_SECURITY_CHARGE
FROM   CCS_IMPORT_UNITS UNI, CCS_LOCAL_ITEM_MASTER MAS, CCS_SETUP_MACRO_VARS SMV, CCS_SETUP_CUSTUM_DUTIES_DETAIL SDD, CCS_SETUP_CUSTUM_DUTIES_HEAD SDH, CCS_SITE_SOURCE_TRANSPORT STR, CCS_STAGE_FREIGHT_AIR FAR
WHERE  UNI.STG_ID = 500
AND    UNI.STG_ID = MAS.STG_ID
AND    UNI.IMU_COD_PRODUCT = MAS.IMU_COD_PRODUCT
AND    UNI.IMU_COD_PRODUCT = STR.IMU_COD_PRODUCT
AND    UNI.STG_ID = SMV.STG_ID
AND    UNI.STG_ID = SDD.STG_ID
AND    UNI.STG_ID = SDH.STG_ID
AND    UNI.STG_ID = STR.STG_ID
AND    SMV.SMV_COD = 'INS'
AND    SDD.SDD_COD = 'GTX'
AND    FAR.STG_ID = STR.STG_ID
AND    FAR.SIS_ID = STR.SIS_ID
AND    FAR.FRM_ID = STR.FRM_ID;



SELECT FAR_INCREASE,
  FAR_AWB_KG_RATES,
  FAR_FUEL_SURCHARGE,
  FAR_SECURITY_CHARGE,
  FAR_OTHER_FFW_FEES,
  STG_ID,
  CUR_ID,
  SIS_ID,
  FRM_ID
FROM CCS_STAGE_FREIGHT_AIR ;
